### PR TITLE
Add coverage for associations without serializers

### PR DESCRIPTION
**Pull request by bf4**
From #955

### CODE REVIEW

**Comment by bf4** [comment]
Due to github weirdness, I left my comments on the wrong url for the third commit https://github.com/rails-api/active_model_serializers/commit/3d98c3c29536b53ae7c3ed1fc5a3bc46e60d4539

**Comment by joaomdmoura** [comment]
@bf4, just merged with some small updates :smile: replaced the `object` for `serialized`

**Comment by bf4** [comment]
Great, I'm glad it worked for you!  (And I'm glad you saw the github comments... I like to link to more permanent commit urls when reference fork/branch work, but I shouldn't have been commenting on it... )

**Comment by joaomdmoura** [comment]
haha no worries, I'm more into comments on PR itself, but it's just a matter of preference :smile:

**Pull request merged**
